# chart/pdvd-backend/templates/deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservice.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "microservice.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "microservice.name" . }}
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: {{ include "microservice.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          env:
            - name: ARANGO_USER
              valueFrom:
                secretKeyRef:
                  name: arangodb
                  key: DBUserName
            - name: ARANGO_PASS
              valueFrom:
                secretKeyRef:
                  name: arangodb
                  key: DBPassword
            - name: ARANGO_HOST
              valueFrom:
                secretKeyRef:
                  name: arangodb
                  key: DBHost
            - name: ARANGO_PORT
              valueFrom:
                secretKeyRef:
                  name: arangodb
                  key: DBPort
            - name: RBAC_REPO
              valueFrom:
                secretKeyRef:
                  name: rbac
                  key: RBACRepo
            - name: RBAC_REPO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: rbac
                  key: RBACRepoToken
            - name: GITHUB_APP_ID
              valueFrom:
                secretKeyRef:
                  name: github
                  key: GITHUB_APP_ID
            - name: GITHUB_APP_NAME
              valueFrom:
                secretKeyRef:
                  name: github
                  key: GITHUB_APP_NAME
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github
                  key: GITHUB_CLIENT_ID
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: github
                  key: GITHUB_CLIENT_SECRET
            - name: GITHUB_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: github
                  key: GITHUB_PRIVATE_KEY
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
---